## Numpy array and basic
learn numpy array and basic operations

In [3]:
import numpy as np

## Creating array from list


In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## List vs Numpy Array

In [ ]:
py_list = [1, 2, 3, 4, 5]
print("Python list:", py_list * 2)

np_array = np.array([1, 2, 3, 4, 5]) # element wise multiplication
print("Numpy array multiplication: " , np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Python list time:", time.time() - start)

 2
print("Numpy array time:", time.time() - start)

Python list: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication:  [ 2  4  6  8 10]
Python list time: 0.39555859565734863
Numpy array time: 0.020369291305541992


## Creating array from scratch

In [ ]:
import numpy as np   # safer way

zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones_array = np.ones((2, 3))
print("Ones array: \n", ones_array)

full = np.full((2, 3), 7)
print("Full array: \n", full)

random = np.random.rand(2, 3)
print("Random array: \n", random) 

sequence = np.arange(0, 10, 3)
print("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7 7]
 [7 7 7]]
Random array: 
 [[0.79189306 0.62615677 0.4269608 ]
 [0.05197629 0.04069281 0.82200373]]
Sequence array: 
 [0 3 6 9]


## Vector, Matrix and Tensor

In [24]:
vector = np.array([1, 2, 3])
print("Vector:\n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)



Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array Shape:", arr.shape)
print("Array Size:", arr.size)
print("Array Dimensions:", arr.ndim)
print("Array Data Type:", arr.dtype)
print("Array Item Size (in bytes):", arr.itemsize)


Array Shape: (2, 3)
Array Size: 6
Array Dimensions: 2
Array Data Type: int64
Array Item Size (in bytes): 8


### Array Reshaping

In [8]:
arr = np.arange(12)
print("Original Array:", arr)

reshaped_arr = arr.reshape((3, 4))
print("Reshaped Array:\n", reshaped_arr)

# flatten (returns a copy of the array collapsed into one dimension)
flattened = reshaped_arr.flatten()
print("Flattened Array:", flattened)

# ravel (returns a flattened array, but is a view if possible)
raveled = reshaped_arr.ravel()
print("Raveled Array:", raveled)

transposed = reshaped_arr.T
print("Transposed Array:\n", transposed)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
