### Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Sclicing", arr[2:7])
print("With step", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Sclicing [3 4 5 6 7]
With step [2 4 6 8]
Negative Indexing 8


In [9]:
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("2D Array slicing", arr_2d[1, 2])
print("Entire Row", arr_2d[1:2])
print("Entire Column", arr_2d[:, 1])

2D Array slicing 6
Entire Row [[4 5 6]]
Entire Column [2 5 8]


### Sorting

In [13]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
sorted_arr = np.sort(unsorted)
print("Sorted Array:", sorted_arr)

arr_2d = np.array([[3, 1, 4],
                    [1, 5, 9],
                    [2, 3, 5]])
print("2D Array sorted by rows:\n", np.sort(arr_2d, axis=1))


Sorted Array: [1 1 2 3 3 4 5 5 5 6 9]
2D Array sorted by rows:
 [[1 3 4]
 [1 5 9]
 [2 3 5]]


### Filter

In [15]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

odd_numbers = numbers[numbers % 2 != 0]
print("Odd Numbers:", odd_numbers)

Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]


### Filter With Mask

In [16]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy Indexing VS np.where()

In [19]:
indices = [0, 3, 5]
print("Numbers at indices:", numbers[indices])

where_result = np.where(numbers > 5)
print("NP Where:", numbers[where_result])

Numbers at indices: [1 4 6]
NP Where: [ 6  7  8  9 10]


In [23]:
conditon_array = np.where(numbers > 5, numbers*4, numbers)
print("Condition Array:", conditon_array)


Condition Array: [ 1  2  3  4  5 24 28 32 36 40]


In [24]:
# Using numpy's where for element-wise condition
result = np.where(numbers > 5, "true", "false")
print(result)
    

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing elements

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concatenated = np.concatenate((arr1, arr2))
print("Concatenated Array:", concatenated)

stacked = np.stack((arr1, arr2))
print("Stacked Array:\n", stacked)

removed_element = np.delete(arr1, 1)
print("Array after removing element at index 1:", removed_element)

Concatenated Array: [1 2 3 4 5 6]
Stacked Array:
 [[1 2 3]
 [4 5 6]]
Array after removing element at index 1: [1 3]


### Array compability

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 5])
c = np.array([7, 8])
print("Compability shape:", a.shape == b.shape)

Compability shape: False


In [ ]:
# Adding a new row (vstack)
original = np.array([[1, 2],[3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("Array after adding new row:\n", with_new_row)

# Adding a new column (hstack)
new_column = np.array([[7],[8],[9]])
with_new_column = np.hstack((with_new_row, new_column))
print("Array after adding new column:\n", with_new_column)


[[1 2]
 [3 4]]
Array after adding new row:
 [[1 2]
 [3 4]
 [5 6]]
Array after adding new column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]
